run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - gofmt
    - goimports
    - misspell
    - nilerr
    - prealloc
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G104 # unhandled errors on deferred Close()
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
    - path: mock_
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 5
