version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - gosec
    - misspell
    - nilerr
    - prealloc
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      excludes:
        - G104
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - unparam
        path: _test\.go
      - linters:
          - unused
        path: mock_
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
